### ISSUE TITLE
Kafkacat doesn't work with bootstrap service

### ISSUE THREAD

**Issue by neverfox** [Yolean/kubernetes-kafka#110]
```
kubectl run -it --rm kafkacat --image=solsson/kafkacat --restart=Never -- -C -b kafka-bootstrap:9200 -t mytopic -p 0 -J -e
```
```
% KC_ERROR: Failed to query metadata for topic mytopic: Local: Broker transport failure
```

It works with the full list of service DNS names and the bootstrap service works just fine with Kafka libraries we're using in code (Java client).

**Comment by solsson** [comment]
Hmm, there was also a negative report about bootstrap.kafka in https://github.com/fluent/fluent-bit-kubernetes-logging/pull/11#issuecomment-352073175.

I don't recognize your port number. And in fact I don't recognize the service name. Where are you running kafkacat? Have you tried with `-d broker`.

**Comment by neverfox** [comment]
Bah, it's the port. Just fat fingered it. As for the service, it's the same one as you have [here](https://github.com/Yolean/kubernetes-kafka/blob/master/kafka/30bootstrap-service.yml), just renamed (since I don't use the kafka namespace).
