### ISSUE TITLE
__consumer_offsets Replication and min insync replica issue

### ISSUE THREAD

**Issue by qrpike** [Yolean/kubernetes-kafka#114]
I have been running a cluster for a day or so now and I was able to write fine, but for some reason the consumer groups would not work. Eventually I found out that the issue was the `__consumer_offsets` topic was saying there wasn't enough insync replicas. 1 was insync, but the minimum was 2. Looking at the kafka manager the replication is only set to one so this would never be achieved. Updating the `min.insync.replicas` to 1 fixed the issue and now everything is working properly. 

Not sure where this is set during the creation of the cluster, but it may be a good idea to fix this for future users. Took a couple hours to figure out the issue and fix it.

**Comment by solsson** [comment]
Were you running from master? Default `2` comes from #107. Was your issue similar #108?

**Comment by qrpike** [comment]
Yea I think I cloned this repo before that merge. It was in the config set to 1.

**Comment by shrinandj** [comment]
This looks the same as #139.

**Comment by solsson** [comment]
I think this is resolved by #140. Anyone with an exiting __consumer_offsets partitions must do something like 49649e1.
