### ISSUE TITLE
externalIp of zk and kf

### ISSUE THREAD

**Issue by alexbelrnd** [Yolean/kubernetes-kafka#129]
Hello, can you please describe how can I expose zk and kf to be available from outside of k8s cluster?

**Comment by solsson** [comment]
What's "kf"? Does https://github.com/Yolean/kubernetes-kafka/issues/124 answer your question?

**Comment by StevenACoffman** [comment]
If you need to expose Kafka outside of the Kubernetes cluster, you should be able to do:
```
kubectl apply -f ./outside-services
```

This will allow you to access Kafka outside your kubernetes cluster like so:
```
#!/bin/bash -x
function join_by { local IFS="$1"; shift; echo "$*"; }

BOOTSTRAP_ARRAY=()
POD_NAME_ARRAY=("kafka-0" "kafka-1" "kafka-2")
for POD_NAME in "${POD_NAME_ARRAY[@]}"
do
  BOOTSTRAP_IP=$(kubectl get pods ${POD_NAME} -n kafka -o jsonpath='{.metadata.labels.kafka-listener-outside-host}')
  BOOTSTRAP_PORT=$(kubectl get pods ${POD_NAME} -n kafka -o jsonpath='{.metadata.labels.kafka-listener-outside-port}')
  BOOTSTRAP_ARRAY+=("$BOOTSTRAP_IP:$BOOTSTRAP_PORT")
done

BOOTSTRAP=$(join_by , "${BOOTSTRAP_ARRAY[@]}")
docker run --rm -t solsson/kafkacat -C -b $BOOTSTRAP -t k8s-firehose -o -10
```
If you want to expose Zookeeper, you can do something similar, but mostly you shouldn't need to. Connecting to Zookeeper first is generally just to get the bootstrap IP and ports.

**Comment by alexbelrnd** [comment]
Thanks
