### ISSUE TITLE
Default offset replication factor not equal to in-sync replic count?

### ISSUE THREAD

**Issue by shrinandj** [Yolean/kubernetes-kafka#139]
I ran into a problem after deploying kafka on my Kubernetes cluster. Whenever my client was using a "group-id", it would fail and get back errors about Marking some broker dead. The reason this happened was that the default `offsets.topic.replication.factor` is 1 whereas `min.insync.replicas` is set to 2.

Some more details can be found [here](https://stackoverflow.com/questions/48536347/kafka-consumer-get-marking-the-coordinator-dead-error-when-using-group-ids).

The fix was to either change the `min.insync.replicas` to 1 or set the `offsets.topic.replication.factor` to 2.

**Comment by solsson** [comment]
I think this is resolved by #140. Anyone with an exiting __consumer_offsets partitions must do something like https://github.com/Yolean/kubernetes-kafka/pull/95/commits/49649e19bb7775165b6f5409211e05840f5c50ef.
