### ISSUE TITLE
kafka-manager  JMX_PORT

### ISSUE THREAD

**Issue by lghinet** [Yolean/kubernetes-kafka#141]
Hello,
by default JMX_PORT = 5555
but kafka-manager cannot reach that port using the outside-(0,1,2) services 

enviroment: kubernetes 1.9.2 (kubeadm); local

any ideas ? 
thanks

**Comment by solsson** [comment]
I think there's nothing special with the JMX port, like with the relation between Kafka's bootstrap flow and listener addresses. You can expose 5555 to remote using any Kubernetes mechanism you like.

**Comment by lghinet** [comment]
if i expose jmx port through kubernetes services, the nodeport will be between 30k-32k ; 
so i will have to change the jmx port from 5555 to something else ... right ?

**Comment by lghinet** [comment]
because kafka manager will try to reach nodeIP:5555

**Comment by solsson** [comment]
I recommend that you run kafka-manager together with your kafka cluster, and expose kafka-manager remotely instead. See #83.

It'd be interesting to be able to use JMX GUIs remotely, and for that I guess it doesn't matter if the port is different.

**Comment by lghinet** [comment]
thank you for your reply,
my brokers host is an external node IP as show in this picture 
![image](https://user-images.githubusercontent.com/12889810/35789696-8d33bd38-0a46-11e8-9541-694746858c77.png)

because i want to reach kafka from outside my kube cluster
according to my picture, kafka-manager will try to reach 10.1.3.79:5555 for logs, which is not open

**Comment by lghinet** [comment]
is there something wrong in my configs ? 
thanks

**Comment by solsson** [comment]
Sorry, IMO external kafka-manager isn't in scope for this repo. Feel free to explore this anyway. If others are interested they will surely find this issue and maybe you can join forces.
