### ISSUE TITLE
Add namespace to rbac-namespace-default

### ISSUE THREAD

**Issue by StevenACoffman** [Yolean/kubernetes-kafka#151]
> We suggest you apply -f manifests in the following order:
>
> You choice of storage classes from ./configure
> ./rbac-namespace-default
> ./zookeeper
> ./kafka

If you add a copy of the `00namespace.yml` to the `rbac-namespace-default` folder, then you can successfully run them in the recommended order.

Sorry I'm not submitting a pull request, but I'm only using my phone at present, and without a laptop it's a bit more tricky than submitting an issue.

**Comment by solsson** [comment]
Safe to do directly in master :)
