### ISSUE TITLE
scale-2 branch not maintained, broken on Minikube 0.25.2

### ISSUE THREAD

**Issue by ldcasillas-progreso** [Yolean/kubernetes-kafka#169]
I upgraded Minikube from 0.25.0 to 0.25.2 and the `scale-2` branch stopped working.  Rather than bother with the technical details of the failure (which I didn't fully investigate), there's a simpler observation to be made: the `scale-2` branch is behind `master` by a couple of months, and simply rebasing `scale-2` on top of the latest `master` fixed it.  

I could submit a pull request bringing it up to date, but it sounds to me like this situation calls first and foremost for a policy decision—either the `single-node` and `scale-2` branches should be actively maintained, or the README should stop directing users to try them and instead document some supported procedure for running a smaller cluster (which could be as simple as instructions on what files to edit to scale the cluster down).

**Comment by solsson** [comment]
I just need a reminder now and then :) Rebased now, thanks.

There's some thoughs of mine about the maintenance situation in https://github.com/Yolean/kubernetes-kafka/pull/44#issuecomment-369127377. I'd be happy to point the readme to forks instead of branches.
