### ISSUE TITLE
Setting Up Kafka Cluster on Bare Metal servers Locally

### ISSUE THREAD

**Issue by rishi007bansod** [Yolean/kubernetes-kafka#201]
Hi,

I have setup my kubernetes cluster on bare-metal servers locally.  Now I want to deploy kafka on this cluster. Which storage class file should I choose from `kubernetes-kafka/configure/` for this deployment. Also what other change are needed if I am running Kafka cluster on local bare metal cluster setup?

Thanks,
Rishikesh

**Comment by solsson** [comment]
You've got to tailor storage classes specifically for your machines. I've actually done some experiments along those lines, in https://github.com/Yolean/youkube/tree/master/local-volume/kafka

I think it would garble the repo to keep such machinespecific files around. To maintain a bare-metal k8s setup you'll probably need quite deep insight into https://kubernetes.io/docs/concepts/storage/volumes/ anyway.

**Comment by rishi007bansod** [comment]
Hi I have tries by using local storage in https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/ but I am getting following error in pzoo-0 pod:

```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  4s (x243 over 20m)  default-scheduler  0/2 nodes are available: 1 node(s) didn't find available persistent volumes to bind, 1 node(s) had taints that the pod didn't tolerate.

```
 i have used following files for storageclass and persistent volume configuration attached in zip file. I have also attached describe log of pod pzoo-0 which gives error. 






[docs.zip](https://github.com/Yolean/kubernetes-kafka/files/2352429/docs.zip)

**Comment by solsson** [comment]
It's unlikely that the error depends on kubernetes-kafka manifests. Did you get a generic StatefulSet to work with local volumes? If you did and you suspect that this repo is somehow incompatible with local volumes, please reopen this issue.

**Comment by rishi007bansod** [comment]
@solsson any idea about this issue why local volumes not working?
