### ISSUE TITLE
Unbound persistance volume claims

### ISSUE THREAD

**Issue by setjet** [Yolean/kubernetes-kafka#213]
Hi,
Just by following the default setup, I am seeing the following error 'pzoo-0: pod has unbound PersistanceVolumeClaims.

The steps I am performing are:
kubectl apply -f configure/minikube-storage-class-broker.yaml
kubectl apply -f configure/minikube-storage-class-zookeeper.yaml
kubectl apply -f 00-namespace.yaml
kubectl apply -f ./rbac-namespace-default
kubectl apply -f ./zookeeper

My k8s version is:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
And minikube version is:
minikube version: v0.28.2

Is this a known issue or something new?

**Comment by solsson** [comment]
You can probably `kubectl describe` those and see why. Could be something with storage classes.

**Comment by setjet** [comment]
Thanks for the quick response! I am still a bit new to kubernetes, but it appears that I can't describe it as the pod is not yet created:

$ kubectl get pods --namespace=kafka
NAME      READY     STATUS    RESTARTS   AGE
pzoo-0    0/1       Pending   0          26s
zoo-0     1/1       Running   0          26s
zoo-1     1/1       Running   0          16s
$ kubectl describe --namespace=kafka pzoo-0
error: the server doesn't have a resource type "pzoo-0"

The same goes when I run it for 'data-pzoo-0', which is a pending PersitantVolumeClaim that seems stuck at pending.

**Comment by setjet** [comment]
Killing that pod data-pzoo-0 pod that was stuck resolved the problem. I think it did not get cleaned up properly when time I deleted it.
