### ISSUE TITLE
how to pass files to container during pod initialization

### ISSUE THREAD

**Issue by catt16** [Yolean/kubernetes-kafka#215]
Hi guys,

I am trying to set up prometheus java agent to monitor kafka metrics. Is there a graceful way to pass the jmx_prometheus_javaagent-0.10.jar file and its config yaml file, prom-jmx-agent-config.yml, to the container, say, under /etc/kafka directory in container?

KAFKA_OPTS=-javaagent:/etc/kafka/jmx_prometheus_javaagent-0.10.jar=707${HOSTNAME##*-}:/etc/kafka/prom-jmx-agent-config.yml;

Thanks for any idea.

**Comment by catt16** [comment]
I am trying to use Prometheus java agent for kafka broker and Grafana for presentation in this repo. Anybody has implemented them already? Appreciate your inputs.

**Comment by solsson** [comment]
Small files can be passed in configmaps or secrets. To experiment with larger files you can keep them in a volume, but building your own images is the preferable way. There are ways to develop images without using an actual image registry, like https://github.com/GoogleContainerTools/skaffold and Minikube's `eval $(minikube docker-env)`.

**Comment by catt16** [comment]
By adding this volume fix the issue, notes mount name should not be conflict with your existing names.
 
volumeMounts:
        - name: libs
          mountPath: /etc/kafka/libs
      volumes:
      - name: libs
        hostPath:
          path: /path to you libs on hosted box

Thanks @solsson .
