### ISSUE TITLE
Increase mem limit on prometheus sidecar

### ISSUE THREAD

**Issue by Jacobh2** [Yolean/kubernetes-kafka#219]
I'm using [50-kafka-jmx-exporter-patch.yml](https://github.com/Yolean/kubernetes-kafka/blob/kafka-2.0.x/prometheus/50-kafka-jmx-exporter-patch.yml) on branch kafka-2.0.x, where the mem limit is set to 120Mi.

After patching and deleting the old kafka pod, I noticed that it got OOM Killed. Increasing to 200Mi to check if that solved the issue started the pod completely and my metrics shows that at some point during startup, the metrics container is using at least 127Mb, suggesting that a limit of 120Mi is not enough.

![image](https://user-images.githubusercontent.com/6471372/48203063-ca991700-e366-11e8-9ca5-6353b8a1ce26.png)

**Comment by solsson** [comment]
Let's give Java 11 a chance, and reopen the issue if we see the same level of memory use after #197.
