### ISSUE TITLE
clients stop receiving messages when kubernetes node becomes NotReady

### ISSUE THREAD

**Issue by atamon** [Yolean/kubernetes-kafka#22]
During a node failure in kubernetes 1/3 kafka pods became unavailable with status "Unknown", this triggered our consuming servicesto stop receiving messages until we restarted them.

The whys and hows behind this is still rather unknown, but we use https://www.npmjs.com/package/no-kafka for clients.

**Comment by solsson** [comment]
To reduce the risk of faults due to inconsistent client behavior we're switching to libs that receive compatibility testing by the Kafka community, as the readme briefly points out since 91b4dde. Let's reopen this issue if we can reproduce it with such clients.
