### ISSUE TITLE
 storageclass.storage.k8s.io "kafka-zookeeper-regional" not found

### ISSUE THREAD

**Issue by guitcastro** [Yolean/kubernetes-kafka#243]
I follow the readme guide to configure the KAFKA in AWS, so I Apply those two configs:

aws-storageclass-zookeeper-managed.yml
aws-storageclass-broker-gp2.yml

When I try to apply the configuration in the zookeeper folder the data-zoo pvc fail to initialize, with error `storageclass.storage.k8s.io "kafka-zookeeper-regional" not found`: I search in the repository for `kafka-zookeeper-regional` and in fact it is only defined in the `configure/minikube-storageclasses.yml` and `configure/gke-regional-euwest1cd-zookeeper-ssd.yml` which as not applied.

```
NAME          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
data-pzoo-0   Bound     pvc-72262760-20e4-11e9-b17e-12dcf5309eca   1Gi        RWO            kafka-zookeeper            2m
data-pzoo-1   Bound     pvc-7227d006-20e4-11e9-b17e-12dcf5309eca   1Gi        RWO            kafka-zookeeper            2m
data-pzoo-2   Bound     pvc-72293b4a-20e4-11e9-b17e-12dcf5309eca   1Gi        RWO            kafka-zookeeper            2m
data-zoo-0    Pending                                                                        kafka-zookeeper-regional   2m
data-zoo-1    Pending   
```  
```

Name:          data-zoo-0
Namespace:     kafka
StorageClass:  kafka-zookeeper-regional
Status:        Pending
Volume:        
Labels:        app=zookeeper
               storage=persistent-regional
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  14s (x14 over 3m)  persistentvolume-controller  storageclass.storage.k8s.io "kafka-zookeeper-regional" not found
```

**Comment by solsson** [comment]
See #241, in particular https://github.com/Yolean/kubernetes-kafka/issues/241#issuecomment-454671374.

Also note that `aks-` and `aws-` is very different examples.

There's nothing contributed yet that corresponds to the GKE example for regional. I can't do aks and aws because I don't have access to such clusters.

**Comment by guitcastro** [comment]
Hello Solsson, thanks the aks was a typo. In fact aws does not currently have regional support so I will just remove it. Thanks
