### ISSUE TITLE
Info about 50kafka.yml

### ISSUE THREAD

**Issue by maykiwo** [Yolean/kubernetes-kafka#245]
Hi 

Could you please the role of volume "extensions" in the 50kafka.yml ?
And what is the contents of this volume because I can't understand where it comes.
thanks for help

**Comment by solsson** [comment]
It lets any init container add jars to kafka's runtime classpath. See #218 for why it was added, and https://github.com/Yolean/kubernetes-kafka/blob/master/cruise-control/20kafka-broker-reporter-patch.yml for an example of how to copy a jar into it.

**Comment by solsson** [comment]
Both those questions are generic Kubernetes topics.
