### ISSUE TITLE
How do you suggest creating topics on startup, thank you

### ISSUE THREAD

**Issue by meirhazonAnyVision** [Yolean/kubernetes-kafka#264]
Hello,
Using your great solution what would be the best way for creating topics on startup?
Thanks so much,
Meir

**Comment by solsson** [comment]
Kubernetes Jobs will by default retry until they succeed. There's an example of how to use kafka' shell scripts at https://github.com/Yolean/kubernetes-kafka/blob/v5.1.0/kafka/test/produce-consume.yml#L60. It's admittedly a resource intensive restart, with a full JVM, but ok for some automation.

**Comment by SoerenHenning** [comment]
I'm curious about the advantages of choosing Kubernetes Jobs over InitContainers in the StatefulSet. Could you explain?

**Comment by marco-jantke** [comment]
@SoerenHenning Isn't it the case that the Kafka server should be running before we can configure topics? Correct me if I'm wrong please.
