### ISSUE TITLE
Kafka MySQL connector example

### ISSUE THREAD

**Issue by guyromb** [Yolean/kubernetes-kafka#275]
Hello,

I am trying to setup an example of a simple MySQL connector (using Yolean Kafka setup). However, I have hard time to find the correct structure/files/commands.

I setup the following:
kafka, zoo, pzoo
avro-rest
avro schemas

I also tried to setup cp-kafka-connect (based on the helm chart), using  kafka bootstrapServers: "PLAINTEXT://bootstrap.kafka:9092" and cp-schema-registry url: "http://avro-schemas.kafka:80"

It is unclear how to setup the connection itself to MySQL / register schemas etc.

**Comment by solsson** [comment]
I think avro tools is a bit outdated. The bootstrap host looks correct. The schema URL you should be able to curl from anywhere in the cluster.
