### ISSUE TITLE
Kafka-cluster with external SSL only

### ISSUE THREAD

**Issue by surmarp** [Yolean/kubernetes-kafka#289]
Hi All,

I want to expose Kafka service outside of kubernetes cluster with SSL support and the internal cluster should be with PLAINTEXT. Any suggestion would be appreciated.

Below is my listener's configuration.

listeners=PLAINTEXT://:9092,OUTSIDE://:9094
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,OUTSIDE:SSL

**Comment by surmarp** [comment]
I have figured out the way and now I am able to expose outside with SSL.

**Comment by bogeit** [comment]
Hello, can you describe the configuration process in detail?
