### ISSUE TITLE
Can't deploy kafka, zookeeper Insufficient memory and cpu

### ISSUE THREAD

**Issue by igorlimansky** [Yolean/kubernetes-kafka#29]
What are minimum specs?
I already have upgraded my agents to have 2 cores and 7gb ram, 50gb ssd, but it still drops me an error for zf-kafkaname-1:

**No nodes are available that match all of the following predicates:: Insufficient cpu (1), Insufficient memory (1).**

How can I fix this?

**Comment by solsson** [comment]
What was your conclusion?

**Comment by igorlimansky** [comment]
@solsson 
oh, sorry, my internet connection dropped and anwser didn't post.
so I figured out, that by default settings I need to have at least 3 agents in cluster with 7gb ram each.
