### ISSUE TITLE
Spring kafka not validating the payload

### ISSUE THREAD

**Issue by sanurani2020** [Yolean/kubernetes-kafka#313]
I've tried both @Valid and @Validated. I've tried adding a MethodValidationPostProcessor bean. I've tried adding a Validator to the KafkaListenerEndpointRegistrar (as per the EnableKafka javadoc):

But no matter what I try, I can still pass invalid requests in and they process without error.
Any help will be appreciated.
@KafkaListener( topics = "${spring.tradeweb.kafka.topic}")
public void onMessage(@Valid @Payload List> records) {
logger.info("received TradewebMessage='{}'", records.size());
List messageList = new ArrayList<>();

Using Spring boot 2.0.5 and kafka 2.1.10

**Comment by solsson** [comment]
Seems unrelated to this repository. Any indication that what you're trying to do works with other Kafka setups but not with this one?

**Comment by sanurani2020** [comment]
My apologies  for posting here , was preparing to post in kafak dev community.
