### ISSUE TITLE
All pods in pending state.

### ISSUE THREAD

**Issue by navinSing** [Yolean/kubernetes-kafka#317]
All pods in pending state.
(Using Bare Metal, ubuntu )

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:54:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

$kubectl -n kafka get all
NAME          READY   STATUS    RESTARTS   AGE
pod/kafka-0   0/1     Pending   0          5m33s
pod/pzoo-0    0/1     Pending   0          5m33s

NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/bootstrap   ClusterIP   10.96.188.103   <none>        9092/TCP            5m33s
service/broker      ClusterIP   None            <none>        9092/TCP            5m33s
service/pzoo        ClusterIP   None            <none>        2888/TCP,3888/TCP   5m33s
service/zoo         ClusterIP   None            <none>        2888/TCP,3888/TCP   5m33s
service/zookeeper   ClusterIP   10.96.186.227   <none>        2181/TCP            5m33s

NAME                     READY   AGE
statefulset.apps/kafka   0/1     5m33s
statefulset.apps/pzoo    0/1     5m33s
statefulset.apps/zoo     0/0     5m33s

```

**Comment by solsson** [comment]
Try `kubectl describe` on statefulset and pods, look at the bottom of the output for reasons why they don't start.

**Comment by FlorinAlexandru** [comment]
I have the same problem with the quickstart example. The output is:
Events:

`  Warning  FailedScheduling  32s (x3 over 107s)  default-scheduler  running "VolumeBinding" filter plugin for pod "pzoo-0": pod has unbound immediate PersistentVolumeClaims`

`Warning  FailedScheduling  16s (x5 over 4m31s)  default-scheduler  running "VolumeBinding" filter plugin for pod "kafka-0": pod has unbound immediate PersistentVolumeClaims`

Should I create persistent volume for dev-small?

**Comment by solsson** [comment]
> Should I create persistent volume for dev-small?
No, it should be automatic.

Can you check status and describe of `pv`s and `pvc`s?

**Comment by FlorinAlexandru** [comment]
> Can you check status and describe of `pv`s and `pvc`s?

I can't manage to reproduce the behavior anymore. I recreated the cluster and now it worked as expected.
