### ISSUE TITLE
advertised hostname issues

### ISSUE THREAD

**Issue by dylanjohnsonsfo** [Yolean/kubernetes-kafka#58]
Works fine until i connect a pub/sub. Seems like the broker is returning the wrong value , shouldn't this be the IP of the broker ? 

socket.gaierror: getaddrinfo failed for kafka:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (calledadvertised.host.name before Kafka 9) correct and resolvable?

**Comment by solsson** [comment]
Are you running current master?

**Comment by dylanjohnsonsfo** [comment]
@solsson yup, the address returned by the broker is not routable, previously I had success by setting the KAFKA_ADVERTISED_HOST_NAME=$KUBERNETES_SERVICE_HOST , wondering why master branch is doing this as it kinda breaks the service.

**Comment by solsson** [comment]
Master's kafka image no longer understands environment variables the way that Confluent Platform and wurstmeister/kafka images do. In Kubernetes such environment is neither practical nor adequate. There's a brief description of the change in https://github.com/Yolean/kubernetes-kafka/issues/13#issuecomment-319159210.
