### ISSUE TITLE
Alternate namespaces + StatefulSet names

### ISSUE THREAD

**Issue by julienvincent** [Yolean/kubernetes-kafka#67]
I'm attempting to run this in an alternate namespace however if I execute the `50kafka StatefulSet` on any namespace other than `kafka` I get the following error:

```
PersistentVolumeClaim is not bound: "data-kafka-0" (repeated 7 times)
```

Zookeeper however runs just fine. I can't spot anything causing this in the kafka StatefulSet - am I missing something?

**Comment by julienvincent** [comment]
Even changing the StatefulSet's `metadata.name` results in the above error.

**Comment by solsson** [comment]
Are you running current master? If so, volume provisioning should be automatic. Maybe that doesn't work in any namespace. Did you try with the default namespace first?

Anyway custom namespace is a perfectly reasonable feature request. For example you might want two separate kafka clusters. The reason for the `namespace:` attributes in yaml is primarily that in my experience it helps in maintenance situations, for example when you do `apply -f`. We could maintain a script to change namespace, analogous to  https://github.com/Yolean/kubernetes-kafka/blob/master/update-kafka-image.sh that changes image.

**Comment by julienvincent** [comment]
@solsson I realized it wasn't actually a provisioning issue. Inspecting the container logs shows me the following error:

```
[2017-09-05 12:33:16,319] FATAL  (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration broker.id: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:713)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:460)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:883)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:867)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:864)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:58)
	at kafka.Kafka.main(Kafka.scala)
```

I'm assuming this is due to some configuration in the kafka image as apposed the config in this repository?

The only reference to `broker.id` I can find was in `10broker-config.yml#11-12` but this shouldn't be influenced by hostname changes

**Comment by julienvincent** [comment]
To confirm, using the default namespace and the default StatefulSet names works as expected

**Comment by solsson** [comment]
This looks like a separate issue again. Maybe the init container failed to deduce a numeric id from the hostname? Can you run `kubectl -c init-config logs [pod name]` to see if it prints any errors? Can you look at the config through `kubectl exec [pod name] -- cat /etc/kafka/server.properties`?

**Comment by julienvincent** [comment]
Finally realized why - completely my fault. Was running the yaml files through `envsubst` to easily change the `metadata.name` properties and didn't realize it was also substituting the environment variables defined in the `data.init.sh` content from the `broker-config` yaml file.
